### ISSUE TITLE
tried running honeybee model on revit 2020 and get a fatal error on run and revit crashs

### ISSUE THREAD

**Issue by arif-hanif** [ladybug-tools/honeybee-revit#6]

**Comment by ksobon** [comment]
Hi Arif,

Can you provide a little bit more information than "it crashed"? If possible please share the Revit model at least so I can try to re-create the issue. 

Cheers! 

-K

**Comment by arif-hanif** [comment]
Sorry @ksobon i was trying to gather the information. Let me know if you need anything else. I was going to try to debug against the VS Solution.

Honey-Revit Version: 1.5.0
Revit Version: 2020.2
OS: Windows 10 x64 Pro

![image](https://user-images.githubusercontent.com/8672758/85050277-d57f7480-b163-11ea-978a-02f26a89ca18.png)

Selecting "Spaces" and clicking run crashes revit.

[R20_Honeybee_TestModel.zip](https://github.com/ladybug-tools/honeybee-revit/files/4800043/R20_Honeybee_TestModel.zip)

**Comment by ksobon** [comment]
Thank you! 

You are the first person outside of me having a look at this, so bear with me through these bugs. I am 100% sure I haven't thought of even half of the possible cases that we will run against. I will have a look at the sample model, and post back here when I have some answers. 

Cheers!

**Comment by ksobon** [comment]
@arif-hanif 

OK, so I had a look at the issue. Basically I suspect that you didn't have Settings defined. In order to run a simulation you would need to have defined a path to the EPW file and a simulation folder. That's why it could have been crashing. I will add notifications to let users know that these have to be set before proceeding. 

I also found that there are certain spaces in the model, that wouldn't process properly due to how Space boundaries were modeled (walls). One particular space is Space: STAFF BREAK AREA 1-094. I added notifications to the UI to let users know if space couldn't be processed. I do admit that I only added one type of error that this space created, but I will expand that in the future. 
![image](https://user-images.githubusercontent.com/529781/85078494-299d4f80-b18a-11ea-83f4-0edc44d7c6b3.png)
I also added functionality to Run/Export buttons to prevent Spaces that cannot be processed to be included in the simulation even if they were selected. Now I can process the model, and create a Honeybee model from it: 
![image](https://user-images.githubusercontent.com/529781/85078602-61a49280-b18a-11ea-9e55-e60b425bd3ac.png)

I will add notifications for the EPW/Simulation folder paths, and publish up a new version for testing. 

Cheers!

**Comment by arif-hanif** [comment]
@ksobon that is great to hear looking forward to running this on a few more models

**Comment by arif-hanif** [comment]
also let me know if you need help with development

**Comment by ksobon** [comment]
@arif-hanif just published a new version. This should work now. Here's the release. https://github.com/ladybug-tools/honeybee-revit/releases/tag/v1.7.0

**Comment by arif-hanif** [comment]
@ksobon thanks, i will give it a go with a few different models. In the end do you need other honey bee items installed on your machine?

**Comment by ksobon** [comment]
@mostaphaRoudsari This is a good question. The simulation requires that we have the Ladybug tools installed. I ran Mingbo's MSI installer for that, but I think it's not publicly available. Is it? We might want to clarify the requirements in a Readme then.

**Comment by mostaphaRoudsari** [comment]
Hi @arif-hanif, yes. you do. @chriswmackey is finalizing the documentation for the Food4Rhino installer that he can share with you. Once you have that the simulation should run successfully.

Also, @arif-hanif , the reason we kept dragonfly schema there with the simplified geometry was for people like yourself who are mainly interested in simplified geometry for load calculation. Looking forward to get your feedback!

**Comment by chriswmackey** [comment]
@arif-hanif ,
Good to hear from you!  To install all of the dependencies other than the Revit plugin itself, you can follow the instructions here:
https://github.com/ladybug-tools/lbt-grasshopper/wiki/1.1-Windows-Installation-Steps
But, instead of downloading anything from Food4Rhino (as the first step says), you should use this grasshopper installer definition here:
https://github.com/ladybug-tools/lbt-grasshopper/blob/master/installer.gh
Also note that there hasn't been a release of Radiance yet so you can skip all of those Radiance steps and just test out the energy modeling side of things.

**Comment by arif-hanif** [comment]
good to hear from you @chriswmackey @mostaphaRoudsari, i am currently working on a project at work would love to speak to you about, are you guys on slack or discord?
